# Generated by Django 3.0.8 on 2020-08-03 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Industry',
            },
        ),
        migrations.CreateModel(
            name='Venture',
            fields=[
                ('venture_id', models.AutoField(primary_key=True, serialize=False)),
                ('venture_name', models.CharField(blank=True, max_length=300, null=True)),
                ('startup_summary', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('investment', models.IntegerField(blank=True, null=True)),
                ('v_linkedin_profile', models.URLField(blank=True, null=True)),
                ('tag_line', models.CharField(blank=True, default=None, max_length=144, null=True)),
                ('location', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('logo_image', models.URLField(blank=True, default=None, null=True)),
                ('main_image', models.URLField(blank=True, default=None, null=True)),
                ('industry', models.ManyToManyField(blank=True, to='entrepreneurs.Industry')),
            ],
            options={
                'verbose_name_plural': 'Ventures',
            },
        ),
        migrations.CreateModel(
            name='PortfolioEnt',
            fields=[
                ('portfolio_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin_profile', models.URLField(blank=True, null=True)),
                ('exec_summary', models.TextField(blank=True, null=True)),
                ('display_image', models.URLField(blank=True, default=None, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrepreneur_portfolio', to=settings.AUTH_USER_MODEL)),
                ('venture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entrepreneurs.Venture')),
            ],
            options={
                'verbose_name_plural': 'Entrepreneur Portfolio',
            },
        ),
    ]
