# Generated by Django 3.0.8 on 2020-08-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioent',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
