# Generated by Django 3.0.6 on 2020-06-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0003_auto_20200604_1523'),
        ('entrepreneurs', '0002_entrepreneurportfoliomodel_linkedin_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepreneurportfoliomodel',
            name='investment_options',
            field=models.ManyToManyField(to='investors.InvestmentOptionsModel'),
        ),
    ]
