# Generated by Django 3.0.6 on 2020-06-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneurs', '0006_auto_20200609_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioent',
            name='prototype',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolioent',
            name='venture_name',
            field=models.CharField(default='ABC Ventures', max_length=300),
            preserve_default=False,
        ),
    ]
