# Generated by Django 3.0.6 on 2020-07-13 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0008_portfolio_current_occupation'),
        ('entrepreneurs', '0008_auto_20200711_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioent',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='portfolioent',
            name='investment',
        ),
        migrations.RemoveField(
            model_name='portfolioent',
            name='investment_options',
        ),
        migrations.RemoveField(
            model_name='portfolioent',
            name='prototype',
        ),
        migrations.RemoveField(
            model_name='portfolioent',
            name='startup_summary',
        ),
        migrations.RemoveField(
            model_name='portfolioent',
            name='venture_name',
        ),
        migrations.CreateModel(
            name='Venture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venture_name', models.CharField(blank=True, max_length=300, null=True)),
                ('startup_summary', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('investment', models.IntegerField(blank=True, null=True)),
                ('industry', models.ManyToManyField(to='entrepreneurs.Industry')),
                ('investment_options', models.ManyToManyField(to='investors.InvestmentOptions')),
            ],
        ),
        migrations.AddField(
            model_name='portfolioent',
            name='venture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entrepreneurs.Venture'),
        ),
    ]
