# Generated by Django 3.0.6 on 2020-07-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0008_portfolio_current_occupation'),
        ('entrepreneurs', '0009_auto_20200713_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venture',
            name='industry',
            field=models.ManyToManyField(blank=True, to='entrepreneurs.Industry'),
        ),
        migrations.AlterField(
            model_name='venture',
            name='investment_options',
            field=models.ManyToManyField(blank=True, to='investors.InvestmentOptions'),
        ),
    ]
