# Generated by Django 3.0.6 on 2020-07-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneurs', '0010_auto_20200714_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='venture',
            name='v_linkedin_profile',
            field=models.URLField(blank=True, null=True),
        ),
    ]
