# Generated by Django 3.0.6 on 2020-07-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneurs', '0011_venture_v_linkedin_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='venture',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venture',
            name='tag_line',
            field=models.CharField(blank=True, default=None, max_length=144, null=True),
        ),
    ]
