# Generated by Django 3.0.6 on 2020-07-21 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneurs', '0012_auto_20200716_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='industry',
            options={'verbose_name_plural': 'Industry'},
        ),
        migrations.AlterModelOptions(
            name='portfolioent',
            options={'verbose_name_plural': 'Entrepreneur Portfolio'},
        ),
        migrations.AlterModelOptions(
            name='venture',
            options={'verbose_name_plural': 'Ventures'},
        ),
        migrations.RemoveField(
            model_name='venture',
            name='investment_options',
        ),
    ]
