# Generated by Django 3.0.8 on 2020-07-30 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneurs', '0013_auto_20200721_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioent',
            name='display_image',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='venture',
            name='logo_image',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='venture',
            name='main_image',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
