# Generated by Django 3.0.8 on 2020-08-03 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entrepreneurs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_history', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Investment History',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('portfolio_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('current_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin_profile', models.URLField(blank=True, null=True)),
                ('background', models.TextField(blank=True, null=True)),
                ('investment', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('num_investments', models.IntegerField(blank=True, null=True)),
                ('display_image', models.URLField(blank=True, default=None, null=True)),
                ('interests', models.ManyToManyField(blank=True, to='entrepreneurs.Industry')),
                ('investment_history', models.ManyToManyField(blank=True, to='investors.History')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investor_portfolio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': "Investor's Portfolio",
            },
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('watchlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('investor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investors.Portfolio')),
                ('ventures', models.ManyToManyField(blank=True, to='entrepreneurs.Venture')),
            ],
            options={
                'verbose_name_plural': 'WatchList',
            },
        ),
    ]
