# Generated by Django 3.0.6 on 2020-05-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_name', models.CharField(max_length=200)),
                ('investor_email', models.EmailField(max_length=254)),
                ('investor_desc', models.CharField(max_length=300)),
                ('investor_money', models.CharField(max_length=20)),
            ],
        ),
    ]
