# Generated by Django 3.0.6 on 2020-06-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0002_investorportfoliomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentHistoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_history', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentOptionsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_option', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Investor',
        ),
        migrations.AddField(
            model_name='investorportfoliomodel',
            name='linkedin_profile',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investorportfoliomodel',
            name='investment_history',
            field=models.ManyToManyField(to='investors.InvestmentHistoryModel'),
        ),
        migrations.AddField(
            model_name='investorportfoliomodel',
            name='investment_options',
            field=models.ManyToManyField(to='investors.InvestmentOptionsModel'),
        ),
    ]
