# Generated by Django 3.0.6 on 2020-06-06 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0004_auto_20200606_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investmentoptions',
            old_name='investment_option',
            new_name='investment_options',
        ),
    ]
