# Generated by Django 3.0.6 on 2020-06-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0007_auto_20200609_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='current_occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
