# Generated by Django 3.0.6 on 2020-07-21 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneurs', '0013_auto_20200721_2201'),
        ('investors', '0010_auto_20200721_2141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name_plural': 'Investment History'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name_plural': "Investor's Portfolio"},
        ),
        migrations.AlterModelOptions(
            name='watchlist',
            options={'verbose_name_plural': 'WatchList'},
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='investment_options',
        ),
        migrations.DeleteModel(
            name='InvestmentOptions',
        ),
    ]
