# Generated by Django 3.0.6 on 2020-07-25 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneurs', '0013_auto_20200721_2201'),
        ('investors', '0011_auto_20200721_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='entrepreneurs',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='ventures',
            field=models.ManyToManyField(blank=True, to='entrepreneurs.Venture'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='investor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investors.Portfolio'),
        ),
    ]
