# Generated by Django 3.0.6 on 2020-07-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneurs', '0013_auto_20200721_2201'),
        ('investors', '0012_auto_20200725_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='interests',
            field=models.ManyToManyField(blank=True, to='entrepreneurs.Industry'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='investment_history',
            field=models.ManyToManyField(blank=True, to='investors.History'),
        ),
    ]
