# Generated by Django 3.0.8 on 2020-07-30 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0013_auto_20200725_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='display_image',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
