# Generated by Django 3.0.6 on 2020-06-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20200609_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_investor',
        ),
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.CharField(choices=[('Investor', 'Investor'), ('Entrepreneur', 'Entrepreneur')], default='Investor', max_length=20),
        ),
    ]
