# Generated by Django 3.0.6 on 2020-06-11 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20200611_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='category',
        ),
    ]
